-- MySQL Script generated by MySQL Workbench
-- Fri Apr  3 10:55:45 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`EquipmentGroup`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`EquipmentGroup` (
  `Id` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  `Description` MEDIUMTEXT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`EquipmentModel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`EquipmentModel` (
  `Id` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  `Brand` VARCHAR(45) NULL,
  `NominalCapacityTons` FLOAT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Equipment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Equipment` (
  `Id` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  `EquipmentGroup_Id` INT NOT NULL,
  `EquipmentModel_Id` INT NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_Equipment_EquipmentGroup_idx` (`EquipmentGroup_Id` ASC) VISIBLE,
  INDEX `fk_Equipment_EquipmentModel1_idx` (`EquipmentModel_Id` ASC) VISIBLE,
  CONSTRAINT `fk_Equipment_EquipmentGroup`
    FOREIGN KEY (`EquipmentGroup_Id`)
    REFERENCES `mydb`.`EquipmentGroup` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Equipment_EquipmentModel1`
    FOREIGN KEY (`EquipmentModel_Id`)
    REFERENCES `mydb`.`EquipmentModel` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`StatusReason`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`StatusReason` (
  `Id` INT NOT NULL,
  `Reason` VARCHAR(45) NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`StatusType`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`StatusType` (
  `Id` INT NOT NULL,
  `Type` VARCHAR(45) NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`StatusEvent`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`StatusEvent` (
  `Id` INT NOT NULL,
  `Equipment_Id` INT NOT NULL,
  `StatusReason_Id` INT NOT NULL,
  `StatusType_Id` INT NOT NULL,
  PRIMARY KEY (`Id`, `StatusType_Id`),
  INDEX `fk_StatusEvent_Equipment1_idx` (`Equipment_Id` ASC) VISIBLE,
  INDEX `fk_StatusEvent_StatusReason1_idx` (`StatusReason_Id` ASC) VISIBLE,
  INDEX `fk_StatusEvent_StatusType1_idx` (`StatusType_Id` ASC) VISIBLE,
  CONSTRAINT `fk_StatusEvent_Equipment1`
    FOREIGN KEY (`Equipment_Id`)
    REFERENCES `mydb`.`Equipment` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_StatusEvent_StatusReason1`
    FOREIGN KEY (`StatusReason_Id`)
    REFERENCES `mydb`.`StatusReason` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_StatusEvent_StatusType1`
    FOREIGN KEY (`StatusType_Id`)
    REFERENCES `mydb`.`StatusType` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`OEMInterface`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`OEMInterface` (
  `Id` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  `Brand` VARCHAR(45) NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`OEMInterfaceMap`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`OEMInterfaceMap` (
  `OEMInterface_Id` INT NOT NULL,
  `Equipment_Id` INT NOT NULL,
  `OEMInterfaceMapcol` VARCHAR(45) NULL,
  INDEX `fk_OEMInterfaceMap_Equipment1_idx` (`Equipment_Id` ASC) VISIBLE,
  PRIMARY KEY (`OEMInterface_Id`),
  CONSTRAINT `fk_OEMInterfaceMap_Equipment1`
    FOREIGN KEY (`Equipment_Id`)
    REFERENCES `mydb`.`Equipment` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_OEMInterfaceMap_OEMInterface1`
    FOREIGN KEY (`OEMInterface_Id`)
    REFERENCES `mydb`.`OEMInterface` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`OEMEventType`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`OEMEventType` (
  `Id` INT NOT NULL,
  `Description` VARCHAR(45) NULL,
  `Other` VARCHAR(45) NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Site`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Site` (
  `Id` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Location`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Location` (
  `Id` INT NOT NULL,
  `Grade` FLOAT NULL,
  `Site_Id` INT NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_Location_Site1_idx` (`Site_Id` ASC) VISIBLE,
  CONSTRAINT `fk_Location_Site1`
    FOREIGN KEY (`Site_Id`)
    REFERENCES `mydb`.`Site` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ShifType`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ShifType` (
  `Id` INT NOT NULL,
  `Type` VARCHAR(45) NULL,
  `Other` TINYTEXT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Shift`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Shift` (
  `Id` INT NOT NULL,
  `ShifType_Id` INT NOT NULL,
  `Date` DATETIME NULL,
  INDEX `fk_Shift_ShifType1_idx` (`ShifType_Id` ASC) VISIBLE,
  PRIMARY KEY (`Id`),
  CONSTRAINT `fk_Shift_ShifType1`
    FOREIGN KEY (`ShifType_Id`)
    REFERENCES `mydb`.`ShifType` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`OEMEvent`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`OEMEvent` (
  `Id` INT NOT NULL,
  `OEMEventType_Id` INT NOT NULL,
  `OEMInterface_Id` INT NOT NULL,
  `Shift_Id` INT NOT NULL,
  `Location_Id` INT NULL,
  `ReadTime` DATETIME NULL,
  `Value` FLOAT NULL,
  `Latitude` FLOAT NULL,
  `Longitude` FLOAT NULL,
  `EquipmentId` VARCHAR(45) NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_OEMEvent_OEMEventType1_idx` (`OEMEventType_Id` ASC) VISIBLE,
  INDEX `fk_OEMEvent_OEMInterface1_idx` (`OEMInterface_Id` ASC) VISIBLE,
  INDEX `fk_OEMEvent_Location1_idx` (`Location_Id` ASC) VISIBLE,
  INDEX `fk_OEMEvent_Shift1_idx` (`Shift_Id` ASC) VISIBLE,
  CONSTRAINT `fk_OEMEvent_OEMEventType1`
    FOREIGN KEY (`OEMEventType_Id`)
    REFERENCES `mydb`.`OEMEventType` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_OEMEvent_OEMInterface1`
    FOREIGN KEY (`OEMInterface_Id`)
    REFERENCES `mydb`.`OEMInterface` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_OEMEvent_Location1`
    FOREIGN KEY (`Location_Id`)
    REFERENCES `mydb`.`Location` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_OEMEvent_Shift1`
    FOREIGN KEY (`Shift_Id`)
    REFERENCES `mydb`.`Shift` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ExchangeType`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ExchangeType` (
  `Id` INT NOT NULL,
  `Type` VARCHAR(45) NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CrewType`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CrewType` (
  `Id` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Operator`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Operator` (
  `Id` INT NOT NULL,
  `FirstName` VARCHAR(45) NULL,
  `LastName` VARCHAR(45) NULL,
  `CrewType_Id` INT NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_Operator_Crew1_idx` (`CrewType_Id` ASC) VISIBLE,
  CONSTRAINT `fk_Operator_Crew1`
    FOREIGN KEY (`CrewType_Id`)
    REFERENCES `mydb`.`CrewType` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ExchangeEvent`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ExchangeEvent` (
  `Id` INT NOT NULL,
  `ExchangeType_Id` INT NOT NULL,
  `Shift_Id` INT NOT NULL,
  `Location_Id` INT NOT NULL,
  `EquipmentTruck_Id` INT NOT NULL,
  `EquipmentExcav_Id` INT NOT NULL,
  `OperatorTruck_Id` INT NOT NULL,
  `OperatorExcav_Id` INT NOT NULL,
  `Latitude` FLOAT NULL,
  `Longitude` FLOAT NULL,
  `MeasuredTons` FLOAT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_ExchangeEvent_ExchangeType1_idx` (`ExchangeType_Id` ASC) VISIBLE,
  INDEX `fk_ExchangeEvent_Shift1_idx` (`Shift_Id` ASC) VISIBLE,
  INDEX `fk_ExchangeEvent_Location1_idx` (`Location_Id` ASC) VISIBLE,
  INDEX `fk_ExchangeEvent_Equipment1_idx` (`EquipmentTruck_Id` ASC) VISIBLE,
  INDEX `fk_ExchangeEvent_Equipment2_idx` (`EquipmentExcav_Id` ASC) VISIBLE,
  INDEX `fk_ExchangeEvent_Operator1_idx` (`OperatorTruck_Id` ASC) VISIBLE,
  INDEX `fk_ExchangeEvent_Operator2_idx` (`OperatorExcav_Id` ASC) VISIBLE,
  CONSTRAINT `fk_ExchangeEvent_ExchangeType1`
    FOREIGN KEY (`ExchangeType_Id`)
    REFERENCES `mydb`.`ExchangeType` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ExchangeEvent_Shift1`
    FOREIGN KEY (`Shift_Id`)
    REFERENCES `mydb`.`Shift` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ExchangeEvent_Location1`
    FOREIGN KEY (`Location_Id`)
    REFERENCES `mydb`.`Location` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ExchangeEvent_Equipment1`
    FOREIGN KEY (`EquipmentTruck_Id`)
    REFERENCES `mydb`.`Equipment` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ExchangeEvent_Equipment2`
    FOREIGN KEY (`EquipmentExcav_Id`)
    REFERENCES `mydb`.`Equipment` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ExchangeEvent_Operator1`
    FOREIGN KEY (`OperatorTruck_Id`)
    REFERENCES `mydb`.`Operator` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ExchangeEvent_Operator2`
    FOREIGN KEY (`OperatorExcav_Id`)
    REFERENCES `mydb`.`Operator` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CrewRegistry`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CrewRegistry` (
  `Id` INT NOT NULL,
  `CrewType_Id` INT NOT NULL,
  `__OperatorList` VARCHAR(45) NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_CrewRegistry_Crew1_idx` (`CrewType_Id` ASC) VISIBLE,
  CONSTRAINT `fk_CrewRegistry_Crew1`
    FOREIGN KEY (`CrewType_Id`)
    REFERENCES `mydb`.`CrewType` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
