Class ASPMining.CanonicalModel.HWMonitoring.OEMInterface Extends %Persistent
{
/// documentation
Property Name As %String;
/// documentation
Property Brand As %String;
Storage Default
{
<Data name="OEMInterfaceDefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>Name</Value>
</Value>
<Value name="3">
<Value>Brand</Value>
</Value>
</Data>
<DataLocation>^ASPMining.CanE4E6.OEMInterfaceD</DataLocation>
<DefaultData>OEMInterfaceDefaultData</DefaultData>
<IdLocation>^ASPMining.CanE4E6.OEMInterfaceD</IdLocation>
<IndexLocation>^ASPMining.CanE4E6.OEMInterfaceI</IndexLocation>
<StreamLocation>^ASPMining.CanE4E6.OEMInterfaceS</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}