Class ASPMining.CanonicalModel.Production.ExchangeType Extends %Persistent
{
	/// documentation
	Property Type As %String;
Storage Default
{
<Data name="ExchangeTypeDefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>Type</Value>
</Value>
</Data>
<DataLocation>^ASPMining.Can4037.ExchangeTypeD</DataLocation>
<DefaultData>ExchangeTypeDefaultData</DefaultData>
<IdLocation>^ASPMining.Can4037.ExchangeTypeD</IdLocation>
<IndexLocation>^ASPMining.Can4037.ExchangeTypeI</IndexLocation>
<StreamLocation>^ASPMining.Can4037.ExchangeTypeS</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}