-- MySQL Script generated by MySQL Workbench
-- Thu Apr 30 20:33:41 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`EquipmentCategory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`EquipmentCategory` (
  `Id` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  `Description` MEDIUMTEXT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`EquipmentModel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`EquipmentModel` (
  `Id` INT NOT NULL,
  `Model` VARCHAR(45) NULL,
  `Brand` VARCHAR(45) NULL,
  `NominalCapacityTons` FLOAT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Equipment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Equipment` (
  `Id` VARCHAR(45) NOT NULL,
  `Name` VARCHAR(45) NULL,
  `Capacity` INT NULL,
  `EquipmentCategory` INT NOT NULL,
  `EquipmentModel` INT NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_Equipment_EquipmentGroup_idx` (`EquipmentCategory` ASC) VISIBLE,
  INDEX `fk_Equipment_EquipmentModel1_idx` (`EquipmentModel` ASC) VISIBLE,
  CONSTRAINT `fk_Equipment_EquipmentGroup`
    FOREIGN KEY (`EquipmentCategory`)
    REFERENCES `mydb`.`EquipmentCategory` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Equipment_EquipmentModel1`
    FOREIGN KEY (`EquipmentModel`)
    REFERENCES `mydb`.`EquipmentModel` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`StatusType`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`StatusType` (
  `Id` INT NOT NULL,
  `Type` VARCHAR(45) NULL,
  `Description` VARCHAR(45) NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`StatusReason`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`StatusReason` (
  `Id` INT NOT NULL,
  `Reason` VARCHAR(45) NULL,
  `Description` VARCHAR(45) NULL,
  `StatusType` INT NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_StatusReason_StatusType1_idx` (`StatusType` ASC) VISIBLE,
  CONSTRAINT `fk_StatusReason_StatusType1`
    FOREIGN KEY (`StatusType`)
    REFERENCES `mydb`.`StatusType` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ShifType`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ShifType` (
  `Id` INT NOT NULL,
  `Type` VARCHAR(45) NULL,
  `Other` TINYTEXT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Crew`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Crew` (
  `Id` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Shift`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Shift` (
  `Id` INT NOT NULL,
  `ShiftType` INT NOT NULL,
  `Crew` INT NOT NULL,
  `DateTime` DATETIME NULL,
  `StartSeconds` INT NULL,
  `StartDay` INT NULL,
  INDEX `fk_Shift_ShifType1_idx` (`ShiftType` ASC) VISIBLE,
  PRIMARY KEY (`Id`),
  INDEX `fk_Shift_Crew1_idx` (`Crew` ASC) VISIBLE,
  CONSTRAINT `fk_Shift_ShifType1`
    FOREIGN KEY (`ShiftType`)
    REFERENCES `mydb`.`ShifType` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Shift_Crew1`
    FOREIGN KEY (`Crew`)
    REFERENCES `mydb`.`Crew` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`StatusEvent`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`StatusEvent` (
  `Id` INT NOT NULL,
  `StatusType` INT NOT NULL,
  `Shift` INT NOT NULL,
  `Equipment` VARCHAR(45) NOT NULL,
  `StatusReason` INT NOT NULL,
  `StartTime` DATETIME NULL,
  `EndTime` DATETIME NULL,
  `Duration` INT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_StatusEvent_Equipment1_idx` (`Equipment` ASC) VISIBLE,
  INDEX `fk_StatusEvent_StatusReason1_idx` (`StatusReason` ASC) VISIBLE,
  INDEX `fk_StatusEvent_StatusType1_idx` (`StatusType` ASC) VISIBLE,
  INDEX `fk_StatusEvent_Shift1_idx` (`Shift` ASC) VISIBLE,
  CONSTRAINT `fk_StatusEvent_Equipment1`
    FOREIGN KEY (`Equipment`)
    REFERENCES `mydb`.`Equipment` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_StatusEvent_StatusReason1`
    FOREIGN KEY (`StatusReason`)
    REFERENCES `mydb`.`StatusReason` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_StatusEvent_StatusType1`
    FOREIGN KEY (`StatusType`)
    REFERENCES `mydb`.`StatusType` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_StatusEvent_Shift1`
    FOREIGN KEY (`Shift`)
    REFERENCES `mydb`.`Shift` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`OEMInterface`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`OEMInterface` (
  `Id` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  `Brand` VARCHAR(45) NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`OEMInterfaceMap`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`OEMInterfaceMap` (
  `OEMInterface_Id` INT NOT NULL,
  `Equipment_Id` INT NOT NULL,
  `OEMInterfaceMapcol` VARCHAR(45) NULL,
  INDEX `fk_OEMInterfaceMap_Equipment1_idx` (`Equipment_Id` ASC) VISIBLE,
  PRIMARY KEY (`OEMInterface_Id`),
  CONSTRAINT `fk_OEMInterfaceMap_Equipment1`
    FOREIGN KEY (`Equipment_Id`)
    REFERENCES `mydb`.`Equipment` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_OEMInterfaceMap_OEMInterface1`
    FOREIGN KEY (`OEMInterface_Id`)
    REFERENCES `mydb`.`OEMInterface` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`OEMEventType`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`OEMEventType` (
  `Id` INT NOT NULL,
  `Description` VARCHAR(45) NULL,
  `Other` VARCHAR(45) NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Site`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Site` (
  `Id` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Location`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Location` (
  `Id` INT NOT NULL,
  `Grade` FLOAT NULL,
  `Site_Id` INT NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_Location_Site1_idx` (`Site_Id` ASC) VISIBLE,
  CONSTRAINT `fk_Location_Site1`
    FOREIGN KEY (`Site_Id`)
    REFERENCES `mydb`.`Site` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`OEMEvent`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`OEMEvent` (
  `Id` INT NOT NULL,
  `OEMEventType_Id` INT NOT NULL,
  `OEMInterface_Id` INT NOT NULL,
  `Shift_Id` INT NOT NULL,
  `Location_Id` INT NULL,
  `ReadTime` DATETIME NULL,
  `Value` FLOAT NULL,
  `Latitude` FLOAT NULL,
  `Longitude` FLOAT NULL,
  `EquipmentId` VARCHAR(45) NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_OEMEvent_OEMEventType1_idx` (`OEMEventType_Id` ASC) VISIBLE,
  INDEX `fk_OEMEvent_OEMInterface1_idx` (`OEMInterface_Id` ASC) VISIBLE,
  INDEX `fk_OEMEvent_Location1_idx` (`Location_Id` ASC) VISIBLE,
  INDEX `fk_OEMEvent_Shift1_idx` (`Shift_Id` ASC) VISIBLE,
  CONSTRAINT `fk_OEMEvent_OEMEventType1`
    FOREIGN KEY (`OEMEventType_Id`)
    REFERENCES `mydb`.`OEMEventType` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_OEMEvent_OEMInterface1`
    FOREIGN KEY (`OEMInterface_Id`)
    REFERENCES `mydb`.`OEMInterface` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_OEMEvent_Location1`
    FOREIGN KEY (`Location_Id`)
    REFERENCES `mydb`.`Location` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_OEMEvent_Shift1`
    FOREIGN KEY (`Shift_Id`)
    REFERENCES `mydb`.`Shift` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Operator`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Operator` (
  `Id` INT NOT NULL,
  `FirstName` VARCHAR(45) NULL,
  `LastName` VARCHAR(45) NULL,
  `Crew` INT NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_Operator_Crew1_idx` (`Crew` ASC) VISIBLE,
  CONSTRAINT `fk_Operator_Crew1`
    FOREIGN KEY (`Crew`)
    REFERENCES `mydb`.`Crew` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`LoadEvent`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`LoadEvent` (
  `Id` INT NOT NULL,
  `DumpEvent` INT NOT NULL,
  `Shift` INT NOT NULL,
  `Location` INT NOT NULL,
  `EquipmentTruck` INT NOT NULL,
  `EquipmentExcav` INT NOT NULL,
  `OperatorTruck` INT NOT NULL,
  `OperatorExcav` INT NOT NULL,
  `Latitude` FLOAT NULL,
  `Longitude` FLOAT NULL,
  `MeasuredTons` FLOAT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_ExchangeEvent_Shift1_idx` (`Shift` ASC) VISIBLE,
  INDEX `fk_ExchangeEvent_Location1_idx` (`Location` ASC) VISIBLE,
  INDEX `fk_ExchangeEvent_Equipment1_idx` (`EquipmentTruck` ASC) VISIBLE,
  INDEX `fk_ExchangeEvent_Equipment2_idx` (`EquipmentExcav` ASC) VISIBLE,
  INDEX `fk_ExchangeEvent_Operator1_idx` (`OperatorTruck` ASC) VISIBLE,
  INDEX `fk_ExchangeEvent_Operator2_idx` (`OperatorExcav` ASC) VISIBLE,
  INDEX `fk_LoadEvent_DumpEvent1_idx` (`DumpEvent` ASC) VISIBLE,
  CONSTRAINT `fk_ExchangeEvent_Shift10`
    FOREIGN KEY (`Shift`)
    REFERENCES `mydb`.`Shift` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ExchangeEvent_Location10`
    FOREIGN KEY (`Location`)
    REFERENCES `mydb`.`Location` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ExchangeEvent_Equipment10`
    FOREIGN KEY (`EquipmentTruck`)
    REFERENCES `mydb`.`Equipment` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ExchangeEvent_Equipment20`
    FOREIGN KEY (`EquipmentExcav`)
    REFERENCES `mydb`.`Equipment` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ExchangeEvent_Operator10`
    FOREIGN KEY (`OperatorTruck`)
    REFERENCES `mydb`.`Operator` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ExchangeEvent_Operator20`
    FOREIGN KEY (`OperatorExcav`)
    REFERENCES `mydb`.`Operator` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_LoadEvent_DumpEvent1`
    FOREIGN KEY (`DumpEvent`)
    REFERENCES `mydb`.`DumpEvent` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`DumpEvent`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`DumpEvent` (
  `Id` INT NOT NULL,
  `LoadEvent` INT NOT NULL,
  `Shift` INT NOT NULL,
  `Location` INT NOT NULL,
  `EquipmentTruck` INT NOT NULL,
  `EquipmentExcav` INT NOT NULL,
  `OperatorTruck` INT NOT NULL,
  `OperatorExcav` INT NOT NULL,
  `Latitude` FLOAT NULL,
  `Longitude` FLOAT NULL,
  `MeasuredTons` FLOAT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_ExchangeEvent_Shift1_idx` (`Shift` ASC) VISIBLE,
  INDEX `fk_ExchangeEvent_Location1_idx` (`Location` ASC) VISIBLE,
  INDEX `fk_ExchangeEvent_Equipment1_idx` (`EquipmentTruck` ASC) VISIBLE,
  INDEX `fk_ExchangeEvent_Equipment2_idx` (`EquipmentExcav` ASC) VISIBLE,
  INDEX `fk_ExchangeEvent_Operator1_idx` (`OperatorTruck` ASC) VISIBLE,
  INDEX `fk_ExchangeEvent_Operator2_idx` (`OperatorExcav` ASC) VISIBLE,
  INDEX `fk_DumpEvent_LoadEvent1_idx` (`LoadEvent` ASC) VISIBLE,
  CONSTRAINT `fk_ExchangeEvent_Shift1`
    FOREIGN KEY (`Shift`)
    REFERENCES `mydb`.`Shift` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ExchangeEvent_Location1`
    FOREIGN KEY (`Location`)
    REFERENCES `mydb`.`Location` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ExchangeEvent_Equipment1`
    FOREIGN KEY (`EquipmentTruck`)
    REFERENCES `mydb`.`Equipment` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ExchangeEvent_Equipment2`
    FOREIGN KEY (`EquipmentExcav`)
    REFERENCES `mydb`.`Equipment` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ExchangeEvent_Operator1`
    FOREIGN KEY (`OperatorTruck`)
    REFERENCES `mydb`.`Operator` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ExchangeEvent_Operator2`
    FOREIGN KEY (`OperatorExcav`)
    REFERENCES `mydb`.`Operator` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DumpEvent_LoadEvent1`
    FOREIGN KEY (`LoadEvent`)
    REFERENCES `mydb`.`LoadEvent` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CrewRegistry`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CrewRegistry` (
  `Id` INT NOT NULL,
  `Crew` INT NOT NULL,
  `__OperatorList` VARCHAR(45) NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_CrewRegistry_Crew1_idx` (`Crew` ASC) VISIBLE,
  CONSTRAINT `fk_CrewRegistry_Crew1`
    FOREIGN KEY (`Crew`)
    REFERENCES `mydb`.`Crew` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
